### ISSUE TITLE
Numérotation dans le plan

### ISSUE THREAD

**Issue by Heresta** [Heresta/Tresors_de_TNAH#44]
Dans certains encodages les numéros de pages dans le plan sont conservés. Pour ma part, je les avais enlevés puisqu'on ne donne pas accès au mémoire en tant que tel. Pensez-vous qu'on doive les garder ou non ?

**Comment by Marie-TNAH** [comment]
Je ne les ai pas gardés non plus. Pour la même raison que toi, je pense qu'il faut les enlever. Donc, non pour moi.

**Comment by TeresaKnapowska** [comment]
Je n'ai pas encore abordé ce problème, mais les numéros de page me semblent importants pour montrer le volume des chapitres et ceraines parties. Je pense qu'il faut les garder, donc plutôt "non".

**Comment by Relais4x100a2** [comment]
> Je ne les ai pas gardés non plus. Pour la même raison que toi, je pense qu'il faut les enlever. Donc, non pour moi.

Idem pour moi, je ne les ai pas gardés pas non plus.

**Comment by chloepochon** [comment]
Très bien, suite à cette discussion je les ai enlevés

**Comment by Heresta** [comment]
Parfait, si la majorité est d'accord, je vais également ajouter cette information dans la documentation.
