### ISSUE TITLE
Ajout dans la documentation

### ISSUE THREAD

**Issue by Heresta** [Heresta/Tresors_de_TNAH#45]
Il y a un document qui est utilisé pour documenter notre choix d'encodage.
Pourrions-nous y ajouter la mention que toute balise autofermante (autre que format) signifie forcément que les informations qui devraient y figurer n'ont pas été fournies ?
Pour <format>, on peut réexpliquer, si ce n'est pas déjà le cas, qu'elle est indiquée autofermante pour qu'elle puisse être utilisée en cas de réutilisation des données de ce dépôt ?

**Comment by YaboulBanwame** [comment]
C'est une très bonne idée, à mon avis.

**Comment by chloepochon** [comment]
Oui, je pense que c'est une bonne idée !

**Comment by Relais4x100a2** [comment]
Je suis d'accord aussi !

**Comment by YaboulBanwame** [comment]
Je pense aussi que c'est une bonne idée.

**Comment by Heresta** [comment]
Etant donné cette majorité qui valide, cela sera ajouté.
